export enum Configuration {
  HOST = 'HOST',
  PORT = 'PORT',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  JWT_EXPIRATION = 'JWT_EXPIRATION',
  FROM_EMAIL = 'FROM_EMAIL',
  EMAIL_USER = 'EMAIL_USER',
  EMAIL_PASSWORD = 'EMAIL_PASSWORD',
}
